**VIT AI Assignment 2 
Ronodeep Das 20BCE1866
ronodeep.das2020@vitstudent.ac.in**

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [192]:
df = pd.read_csv('content/drug200.csv')
df.head()
df.tail()


Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

**Part 1. Data Preprocessing**

In [113]:
df.describe(include='all')

Age  Sex    BP Cholesterol     Na_to_K   Drug
count   200.000000  200   200         200  200.000000    200
unique         NaN    2     3           2         NaN      5
top            NaN    M  HIGH        HIGH         NaN  DrugY
freq           NaN  104    77         103         NaN     91
mean     44.315000  NaN   NaN         NaN   16.084485    NaN
std      16.544315  NaN   NaN         NaN    7.223956    NaN
min      15.000000  NaN   NaN         NaN    6.269000    NaN
25%      31.000000  NaN   NaN         NaN   10.445500    NaN
50%      45.000000  NaN   NaN         NaN   13.936500    NaN
75%      58.000000  NaN   NaN         NaN   19.380000    NaN
max      74.000000  NaN   NaN         NaN   38.247000    NaN

In [10]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [75]:
le = LabelEncoder() 

In [193]:
y = pd.get_dummies(df.iloc[:,5:]).values
y

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1,

In [194]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [195]:
x = df.iloc[:,0:5]
x.head()

Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043

In [196]:
x['BP'] = le.fit_transform(x['BP'])
x['BP']

0      0
1      1
2      1
3      2
4      1
      ..
195    1
196    1
197    2
198    2
199    1
Name: BP, Length: 200, dtype: int64

In [197]:
x['Sex'] = le.fit_transform(x['Sex'])
x['Sex']

0      0
1      1
2      1
3      0
4      0
      ..
195    0
196    1
197    1
198    1
199    0
Name: Sex, Length: 200, dtype: int64

In [198]:
x['Cholesterol'] = le.fit_transform(x['Cholesterol'])
x['Cholesterol']

0      0
1      0
2      0
3      0
4      0
      ..
195    0
196    0
197    0
198    1
199    1
Name: Cholesterol, Length: 200, dtype: int64

In [199]:
x.head()

Age  Sex  BP  Cholesterol  Na_to_K
0   23    0   0            0   25.355
1   47    1   1            0   13.093
2   47    1   1            0   10.114
3   28    0   2            0    7.798
4   61    0   1            0   18.043

In [200]:
x=x.values

In [201]:
x

array([[23.   ,  0.   ,  0.   ,  0.   , 25.355],
       [47.   ,  1.   ,  1.   ,  0.   , 13.093],
       [47.   ,  1.   ,  1.   ,  0.   , 10.114],
       [28.   ,  0.   ,  2.   ,  0.   ,  7.798],
       [61.   ,  0.   ,  1.   ,  0.   , 18.043],
       [22.   ,  0.   ,  2.   ,  0.   ,  8.607],
       [49.   ,  0.   ,  2.   ,  0.   , 16.275],
       [41.   ,  1.   ,  1.   ,  0.   , 11.037],
       [60.   ,  1.   ,  2.   ,  0.   , 15.171],
       [43.   ,  1.   ,  1.   ,  1.   , 19.368],
       [47.   ,  0.   ,  1.   ,  0.   , 11.767],
       [34.   ,  0.   ,  0.   ,  1.   , 19.199],
       [43.   ,  1.   ,  1.   ,  0.   , 15.376],
       [74.   ,  0.   ,  1.   ,  0.   , 20.942],
       [50.   ,  0.   ,  2.   ,  0.   , 12.703],
       [16.   ,  0.   ,  0.   ,  1.   , 15.516],
       [69.   ,  1.   ,  1.   ,  1.   , 11.455],
       [43.   ,  1.   ,  0.   ,  0.   , 13.972],
       [23.   ,  1.   ,  1.   ,  0.   ,  7.298],
       [32.   ,  0.   ,  0.   ,  1.   , 25.974],
       [57.   ,  1. 

In [202]:
from sklearn.model_selection import train_test_split

In [203]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [204]:

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=21)

In [206]:

xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((160, 5), (40, 5), (160, 5), (40, 5))

**Part 2 . Build ANN Model**

In [207]:

# ANN Model

model = Sequential()
#input layer
model.add(Dense(8,input_dim=5,activation='sigmoid'))
#hidden layer 1
model.add(Dense(32,activation='sigmoid'))
#hidden layer 2
model.add(Dense(26,activation='sigmoid'))
#hidden layer 3
model.add(Dense(26,activation='sigmoid'))
#output layer
model.add(Dense(5,activation='softmax'))

In [208]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [181]:

model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_45 (Dense)            (None, 8)                 48        
                                                                 
 dense_46 (Dense)            (None, 32)                288       
                                                                 
 dense_47 (Dense)            (None, 26)                858       
                                                                 
 dense_48 (Dense)            (None, 26)                702       
                                                                 
 dense_49 (Dense)            (None, 1)                 27        
                                                                 
Total params: 1,923
Trainable params: 1,923
Non-trainable params: 0
_________________________________________________________________


**Part 3.Test Model with Random Data**

In [209]:
model.fit(xtrain,ytrain,epochs=30,batch_size=5,validation_data=(xtest,ytest))


Epoch 1/30
32/32 [==============================] - 1s 9ms/step - loss: 1.9032 - accuracy: 0.1250 - val_loss: 1.6721 - val_accuracy: 0.1750
Epoch 2/30
32/32 [==============================] - 0s 3ms/step - loss: 1.5064 - accuracy: 0.3125 - val_loss: 1.4005 - val_accuracy: 0.5250
Epoch 3/30
32/32 [==============================] - 0s 3ms/step - loss: 1.3868 - accuracy: 0.4375 - val_loss: 1.3628 - val_accuracy: 0.5250
Epoch 4/30
32/32 [==============================] - 0s 4ms/step - loss: 1.3683 - accuracy: 0.4375 - val_loss: 1.3641 - val_accuracy: 0.5250
Epoch 5/30
32/32 [==============================] - 0s 4ms/step - loss: 1.3640 - accuracy: 0.4375 - val_loss: 1.3640 - val_accuracy: 0.5250
Epoch 6/30
32/32 [==============================] - 0s 3ms/step - loss: 1.3647 - accuracy: 0.4375 - val_loss: 1.3685 - val_accuracy: 0.5250
Epoch 7/30
32/32 [==============================] - 0s 4ms/step - loss: 1.3605 - accuracy: 0.4375 - val_loss: 1.3608 - val_accuracy: 0.5250
Epoch 8/30
32/32 [==

In [210]:
model.predict(xtest)

2/2 [==============================] - 0s 6ms/step


array([[0.13597046, 0.14953274, 0.10388247, 0.12429595, 0.48631838],
       [0.721524  , 0.08737375, 0.03990736, 0.05088045, 0.10031445],
       [0.605149  , 0.11228122, 0.05488049, 0.06959382, 0.1580955 ],
       [0.5679599 , 0.1188732 , 0.05935383, 0.07524716, 0.1785659 ],
       [0.04492837, 0.12522727, 0.10311754, 0.12195407, 0.6047727 ],
       [0.46799478, 0.1345595 , 0.07129367, 0.08970953, 0.23644258],
       [0.78270596, 0.07225397, 0.0318836 , 0.04051602, 0.07264041],
       [0.6236287 , 0.10857752, 0.05249655, 0.06670672, 0.1485905 ],
       [0.05960602, 0.13161567, 0.10421143, 0.12346817, 0.5810987 ],
       [0.7467622 , 0.08136696, 0.03663531, 0.04665286, 0.08858258],
       [0.7680738 , 0.07602466, 0.03381935, 0.04302915, 0.07905302],
       [0.11786719, 0.14575246, 0.10363176, 0.1244839 , 0.50826466],
       [0.0554058 , 0.13003695, 0.1040711 , 0.12315025, 0.5873358 ],
       [0.04572659, 0.12564468, 0.10322218, 0.12206887, 0.60333765],
       [0.08837695, 0.141132  , 0.

In [211]:
ar=[[23,1,0,0,11],[56,0,1,1,10],[19,1,2,0,7.67]]
dd=pd.DataFrame(ar)
model.predict(dd)

1/1 [==============================] - 0s 397ms/step


array([[0.650022  , 0.10327968, 0.04916809, 0.06253039, 0.13499977],
       [0.05118028, 0.12831469, 0.10384769, 0.12276977, 0.5938875 ],
       [0.07689619, 0.13708529, 0.10444245, 0.12432935, 0.5572467 ]],
      dtype=float32)